#!/usr/bin/with-contenv bashio
# ==============================================================================
# Ryobi GDO Local Server — Home Assistant Add-on entrypoint
#
# This script:
#  1. Reads user options from /data/options.json (set via HA UI)
#  2. Detects the host's LAN IP address (so dnsmasq knows what to advertise)
#  3. Writes a dnsmasq config that resolves tti.tiwiconnect.com → host IP
#  4. Starts dnsmasq in background (DNS server on port 53)
#  5. Writes the ryobi server config from options
#  6. Starts the Python ryobi-local-server in foreground
# ==============================================================================

set -e

bashio::log.info "Starting Ryobi GDO Local Server Add-on..."

# ---------------------------------------------------------------------------
# Read options from HA UI (stored at /data/options.json by Supervisor)
# ---------------------------------------------------------------------------
DEVICE_ID="$(bashio::config 'device_id')"
DEVICE_NAME="$(bashio::config 'device_name' 'Garage Door')"
LOG_LEVEL="$(bashio::config 'log_level' 'info')"
SERVER_PORT="$(bashio::config 'server_port' '80')"
DNS_ENABLED="$(bashio::config 'dns_enabled' 'true')"
DNS_PORT="$(bashio::config 'dns_port' '53')"
COMMAND_WEBHOOK_URL="$(bashio::config 'command_webhook_url' '')"
COMMAND_WEBHOOK_TIMEOUT="$(bashio::config 'command_webhook_timeout' '3')"
INGRESS_PORT="$(bashio::addon.ingress_port)"

if bashio::var.is_empty "${DEVICE_ID}"; then
    bashio::log.fatal "device_id is required! Set it in the add-on configuration."
    exit 1
fi

bashio::log.info "Device ID:   ${DEVICE_ID}"
bashio::log.info "Device Name: ${DEVICE_NAME}"
bashio::log.info "Server Port: ${SERVER_PORT}"
bashio::log.info "DNS Enabled: ${DNS_ENABLED}"
bashio::log.info "Log Level:   ${LOG_LEVEL}"

# ---------------------------------------------------------------------------
# Detect host LAN IP
# We use the default route interface to find the IP that other LAN devices
# will use to reach this machine (e.g. 192.168.1.100).
# ---------------------------------------------------------------------------
HOST_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
if bashio::var.is_empty "${HOST_IP}"; then
    # Fallback: grab first non-loopback IP
    HOST_IP="$(hostname -i | tr ' ' '\n' | grep -v '^127\.' | grep -v '^::1' | head -1)"
fi

bashio::log.info "Detected host IP: ${HOST_IP}"

# ---------------------------------------------------------------------------
# Configure dnsmasq
# ---------------------------------------------------------------------------
DNSMASQ_CONF="/etc/dnsmasq.d/ryobi.conf"

if [ "${DNS_ENABLED}" = "true" ]; then
    bashio::log.info "Configuring dnsmasq on port ${DNS_PORT}..."

    # Build dnsmasq config:
    # - Resolve tti.tiwiconnect.com → host IP (where our HTTP server runs)
    # - Forward all other DNS to upstream (1.1.1.1 / 8.8.8.8)
    # - Listen on all interfaces so LAN devices can query us
    cat > /etc/dnsmasq.conf <<EOF
# Ryobi GDO Local Server — dnsmasq configuration
# Auto-generated by run.sh — do not edit manually

port=${DNS_PORT}
no-resolv
no-poll

# Upstream DNS servers (used for everything except tti.tiwiconnect.com)
server=1.1.1.1
server=8.8.8.8

# Redirect Ryobi cloud to local server
address=/tti.tiwiconnect.com/${HOST_IP}

# Listen on all interfaces
listen-address=0.0.0.0
bind-interfaces

# Log queries (useful for debugging)
log-queries
log-facility=/proc/1/fd/1

# Reduce TTL so clients pick up changes quickly
local-ttl=10
EOF

    bashio::log.info "Starting dnsmasq..."
    dnsmasq --no-daemon &
    DNSMASQ_PID=$!
    bashio::log.info "dnsmasq started (PID: ${DNSMASQ_PID})"

    # Also update /etc/resolv.conf inside the addon container so the Python
    # server itself resolves tti.tiwiconnect.com → localhost when cloud_poll is on
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "nameserver 1.1.1.1" >> /etc/resolv.conf

    bashio::log.info "DNS redirect active: tti.tiwiconnect.com -> ${HOST_IP}"
    bashio::log.info ""
    bashio::log.info "============================================================"
    bashio::log.info "  Point your router's DNS to: ${HOST_IP}"
    bashio::log.info "  OR add to each device's DNS settings: ${HOST_IP}"
    bashio::log.info "  tti.tiwiconnect.com will resolve to ${HOST_IP}:${SERVER_PORT}"
    bashio::log.info "============================================================"
    bashio::log.info ""
else
    bashio::log.info "DNS disabled — skipping dnsmasq."
    bashio::log.info "You must manually redirect tti.tiwiconnect.com -> ${HOST_IP}"
fi

# ---------------------------------------------------------------------------
# Build the ryobi server config file from HA options
# ---------------------------------------------------------------------------
CONFIG_FILE="/data/ryobi_server_config.yaml"

cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by Ryobi GDO Local Server add-on
# Edit via Home Assistant add-on configuration UI, not here.

devices:
  - device_id: "${DEVICE_ID}"
    name: "${DEVICE_NAME}"
    modules:
      garageDoor: "garageDoor_7"
      garageLight: "garageLight_7"
      backupCharger: "backupCharger_6"
      wifiModule: "wifiModule_7"
      parkAssistLaser: "parkAssistLaser_1"
      inflator: "inflator_4"
      btSpeaker: "btSpeaker_2"
      fan: "fan_3"

cloud_poll: false
enforce_token: false

$(if ! bashio::var.is_empty "${COMMAND_WEBHOOK_URL}"; then
    echo "command_webhook_url: \"${COMMAND_WEBHOOK_URL}\""
    echo "command_webhook_timeout: ${COMMAND_WEBHOOK_TIMEOUT}"
fi)
EOF

bashio::log.info "Server config written to ${CONFIG_FILE}"

# ---------------------------------------------------------------------------
# Generate SSL certificate for TLS / HTTPS / WSS port 443
# ---------------------------------------------------------------------------
SSL_DIR="/data/ssl"
mkdir -p "${SSL_DIR}"

if [ ! -f "${SSL_DIR}/server.crt" ] || [ ! -f "${SSL_DIR}/server.key" ]; then
    bashio::log.info "Generating self-signed TLS certificate for tti.tiwiconnect.com..."
    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "${SSL_DIR}/server.key" \
        -out "${SSL_DIR}/server.crt" \
        -days 3650 \
        -subj "/CN=tti.tiwiconnect.com" \
        -addext "subjectAltName=DNS:tti.tiwiconnect.com,DNS:tti-prod2.thomisidae.com,IP:${HOST_IP}" || true
fi

# ---------------------------------------------------------------------------
# Start the Ryobi local server (HTTP 80 + HTTPS 443 + Ingress 8099)
# ---------------------------------------------------------------------------
bashio::log.info "Starting Ryobi server on ports ${SERVER_PORT} (HTTP), 443 (HTTPS), and ${INGRESS_PORT} (Ingress)..."

python3 -m server.main \
    --config "${CONFIG_FILE}" \
    --host 0.0.0.0 \
    --port "${SERVER_PORT}" \
    --ssl-port 443 \
    --ssl-cert "${SSL_DIR}/server.crt" \
    --ssl-key "${SSL_DIR}/server.key" \
    --ingress-port "${INGRESS_PORT}" \
    --log-level "$(echo ${LOG_LEVEL} | tr '[:lower:]' '[:upper:]')" &

MAIN_PID=$!
bashio::log.info "Ryobi local server started (PID: ${MAIN_PID})"

bashio::log.info ""
bashio::log.info "Ryobi GDO Local Server is running!"
bashio::log.info "  HTTP:    http://${HOST_IP}:${SERVER_PORT}/api/devices"
bashio::log.info "  HTTPS:   https://${HOST_IP}:443/api/devices"
bashio::log.info "  State:   http://${HOST_IP}:${SERVER_PORT}/state"
bashio::log.info "  Health:  http://${HOST_IP}:${SERVER_PORT}/health"
bashio::log.info ""

# ---------------------------------------------------------------------------
# Keep alive — monitor main server process
# ---------------------------------------------------------------------------
wait ${MAIN_PID}
EXIT_CODE=$?
bashio::log.warning "Ryobi server exited with code ${EXIT_CODE}"

# Clean up dnsmasq if it was started
if [ -n "${DNSMASQ_PID:-}" ]; then
    kill "${DNSMASQ_PID}" 2>/dev/null || true
fi

exit ${EXIT_CODE}
